#!/bin/bash

while getopts ":o:f:" opt; do
    case $opt in
        f)
            if [[ "$OPTARG" == "true" || "$OPTARG" == "false" ]]; then
                first=$OPTARG
            else
                echo "Invalid value for -f. Use 'true' or 'false'." >&2
                exit 1
            fi
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done
shift $((OPTIND -1))

if [ -z "$first" ]; then
    echo "Setup type is required. Use -f to specify the setup type."
    exit 1
fi

pressures=("$@")
if [ ! -d "results" ]; then
    mkdir results
fi
echo "pressure = ${pressures[@]}" > results/pressures.txt


for pressure in ${pressures[@]}; do
    echo "Pressure: $pressure"
    sed -i '' "s/pressure = .*/pressure = $pressure/" config.cfg
    dirName="pressure-${pressure//./_}"

    if [ "$first" == "true" ]; then
        sed -i '' "s/setup = .*/setup = cubic/" config.cfg
        restartDir=$dirName
        first=false
    else
        sed -i '' "s/setup = .*/setup = restart/" config.cfg
        restartDir=$(echo $restartDir | tr -d '"')
        echo "Restart directory: $restartDir"
    
        last_file=$(ls -1 "$restartDir/props/" | sort -t_ -k2,2n | tail -n 1)
    fi

    ./run Release
    restartDir=$dirName
done

mv pressure-* results